name: Create standalone installers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build installer on ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: win64
          - os: ubuntu-latest
            name: linux
          - os: macos-13
            name: macos
          - os: macos-latest
            name: arm64-macos
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: matlab-actions/setup-matlab@v2
        with:
          # You should add all the products that you need here. The names have to match
          # the ones in this document: https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/mpm-input-files/R2024a/mpm_input_r2024a.txt#L67
          products: >
            MATLAB_Compiler

      - name: Run installer
        run: |
          matlab-batch -licenseToken "${{ secrets.MATLAB_LICENSE_TOKEN }}" 'buildResults = compiler.build.standaloneApplication("app.mlapp"); compiler.package.installer(buildResults, "OutputDir", "./installer", "InstallerName", "app-${{ matrix.name }}")'

      - uses: actions/upload-artifact@v4
        with:
          path: installer
